# Generated by Django 4.1.2 on 2022-10-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movie_app", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                choices=[(1, "*"), (2, "**"), (3, "***"), (4, "****"), (5, "*****")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movie", name="duration", field=models.DurationField(null=True)
        ),
    ]
