# Generated by Django 4.1.2 on 2022-10-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("movie_app", "0002_review_stars_alter_movie_duration")]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie_app.movie",
            ),
        )
    ]
