# Generated by Django 4.1.2 on 2022-10-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movie_app", "0004_alter_review_movie")]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                choices=[(1, "*"), (2, "**"), (3, "***"), (4, "****"), (5, "*****")],
                default=3,
            ),
        )
    ]
